"""Added title column for bookmark class.

Revision ID: 0c9a1861cb36
Revises: c31f06275fe4
Create Date: 2016-12-27 15:07:04.501686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9a1861cb36'
down_revision = 'c31f06275fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark', 'title')
    # ### end Alembic commands ###
