"""Drop date_created and re-add.

Revision ID: 3448945a5d97
Revises: 681358abc387
Create Date: 2016-12-29 14:51:38.017517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3448945a5d97'
down_revision = '681358abc387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.add_column('bookmark', sa.Column('created_dateb', sa.DateTime(), nullable=True))
    op.drop_column('bookmark', 'created_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('bookmark', 'created_dateb')
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
