"""Added bookmark and tag relation to User.

Revision ID: f3df4e5d91da
Revises: 6ec3c76f372e
Create Date: 2016-12-30 13:06:51.929789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3df4e5d91da'
down_revision = '6ec3c76f372e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookmark', 'user', ['user_id'], ['id'])
    op.add_column('tag', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tag', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'user_id')
    op.drop_constraint(None, 'bookmark', type_='foreignkey')
    op.drop_column('bookmark', 'user_id')
    # ### end Alembic commands ###
